---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-order-config
  namespace: stockxpress
  labels:
    app: mysql-order
    component: database
data:
  database-name: order_service
  mysql-port: "3306"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-inventory-config
  namespace: stockxpress
  labels:
    app: mysql-inventory
    component: database
data:
  database-name: inventory_service
  mysql-port: "3306"
